package:
  name: gsi_stuff
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.1.0') }}

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: python
  script: $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
  run:

about:
    home:
